DROP TABLE IF EXISTS roles;
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

INSERT INTO roles (id, name)
SELECT 1, 'Admin'
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE id = 1);

INSERT INTO roles (id, name)
SELECT 2, 'Master'
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE id = 2);

INSERT INTO roles (id, name)
SELECT 3, 'Jugador'
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE id = 3);
